version: '3'
services:
  mariadb:
    image: mariadb:11
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./attacklogdata:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./services/cowrie/cowrie-sql:/cowrie-sql
      - ./backend:/backend

  ssh_honeypot:
    image: cowrie/cowrie:latest
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - ./services/cowrie/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg 
      - ./services/cowrie/logs:/opt/cowrie/log
      - ./services/cowrie/mysql.py:/cowrie/cowrie-git/src/cowrie/output/mysql.py

  dionaea_honeypot:
    image: dinotools/dionaea
    restart: always
    environment:
      DIONAEA_FORCE_INIT: "1"  # Prevents overwriting directory on start
    ports:
      # - "21:21"
      # - "42:42"
      # - "69:69"
      - "80:80"
      # - "135:135"
      - "443:443"
      # - "445:445"
      # - "1433:1433"
      # - "3306:3306"
      # - "5060:5060"
      # - "5061:5061"
    volumes:
      - ./services/dionaea/log:/opt/dionaea/var/log/dionaea
      - ./services/dionaea/data/dionaea.sqlite:/opt/dionaea/var/lib/dionaea/dionaea.sqlite
