# Base image
FROM dinotools/dionaea:latest

# Copy custom configuration files into the container
COPY config/your-service.yaml /opt/dionaea/etc/dionaea/services-enabled/
COPY config/your-ihandler.yaml /opt/dionaea/etc/dionaea/ihandlers-enabled/
